###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": null
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": " "
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task"
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": " "
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": "doesntexist"
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": "c60637d20bde4f95b6e8d40e55a41298"
}

###
GET http://127.0.0.1:5000/api/v1.0/task/63b78fefb173427b9872ab577cbfa7c1 HTTP/1.1
content-type: application/json


###
GET http://127.0.0.1:5000/api/v1.0/task/all HTTP/1.1
content-type: application/json

###
PUT http://127.0.0.1:5000/api/v1.0/task/63b78fefb173427b9872ab577cbfa7c1 HTTP/1.1
content-type: application/json

{
  "name": "Task edited"
}

###
PUT http://127.0.0.1:5000/api/v1.0/task/63b78fefb173427b9872ab577cbfa7c1 HTTP/1.1
content-type: application/json

{
  "completed": true
}

###
DELETE http://127.0.0.1:5000/api/v1.0/task/63b78fefb173427b9872ab577cbfa7c1 HTTP/1.1
content-type: application/json
