###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": null
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": " "
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task"
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": " "
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": "doesntexist"
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": "78d104f85b61447db27d11a4caa89a0e"
}

### Retrieve non existing record
GET http://127.0.0.1:5000/api/v1.0/task/not_exist HTTP/1.1
content-type: application/json


### Retrieve existing record
GET http://127.0.0.1:5000/api/v1.0/task/5c002b4b9c7e4e179a90153852a085bc HTTP/1.1
content-type: application/json


###
GET http://127.0.0.1:5000/api/v1.0/task/all HTTP/1.1
content-type: application/json

###
PUT http://127.0.0.1:5000/api/v1.0/task/5c002b4b9c7e4e179a90153852a085bc HTTP/1.1
content-type: application/json

{
  "name": " "
}

###
PUT http://127.0.0.1:5000/api/v1.0/task/5c002b4b9c7e4e179a90153852a085bc HTTP/1.1
content-type: application/json

{
  "name": "Task edited"
}

###
PUT http://127.0.0.1:5000/api/v1.0/task/5c002b4b9c7e4e179a90153852a085bc HTTP/1.1
content-type: application/json

{
  "completed": true
}

###
DELETE http://127.0.0.1:5000/api/v1.0/task/5c002b4b9c7e4e179a90153852a085bc HTTP/1.1
content-type: application/json
