###
POST http://127.0.0.1:5000/api/v1.0/project HTTP/1.1
Content-Type: application/json

{
  "name": "Project 2",
  "color": "#000000"
}

###
GET http://127.0.0.1:5000/api/v1.0/project/all HTTP/1.1
content-type: application/json

###
GET http://127.0.0.1:5000/api/v1.0/project/43dd666a9b7e4d0dbff34c126d6d24c7 HTTP/1.1
content-type: application/json

### 
PUT http://127.0.0.1:5000/api/v1.0/project/43dd666a9b7e4d0dbff34c126d6d24c7 HTTP/1.1
content-type: application/json

{
  "name": "New Project edited"
}

###
PUT http://127.0.0.1:5000/api/v1.0/project/43dd666a9b7e4d0dbff34c126d6d24c7 HTTP/1.1
content-type: application/json

{
  "name": "New Project edited 8",
  "color": "#fa11ff"
}

###
DELETE http://127.0.0.1:5000/api/v1.0/project/43dd666a9b7e4d0dbff34c126d6d24c7 HTTP/1.1
content-type: application/json
