###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": null
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": " "
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task"
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": " "
}

###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": "doesntexist"
}
###
POST http://127.0.0.1:5000/api/v1.0/task HTTP/1.1
Content-Type: application/json

{
  "name": "New api/v1.0/task",
  "project_id": "d10a576cbd504734bb6a80cd85124b56"
}

###
GET http://127.0.0.1:5000/api/v1.0/task/e71a65a62bc7417097ae906afb88fc4b HTTP/1.1
content-type: application/json


###
GET http://127.0.0.1:5000/api/v1.0/task/all HTTP/1.1
content-type: application/json

###
PUT http://127.0.0.1:5000/api/v1.0/task/e71a65a62bc7417097ae906afb88fc4b HTTP/1.1
content-type: application/json

{
  "name": " "
}

###
PUT http://127.0.0.1:5000/api/v1.0/task/e71a65a62bc7417097ae906afb88fc4b HTTP/1.1
content-type: application/json

{
  "name": "Task edited"
}

###
PUT http://127.0.0.1:5000/api/v1.0/task/e71a65a62bc7417097ae906afb88fc4b HTTP/1.1
content-type: application/json

{
  "completed": true
}

###
DELETE http://127.0.0.1:5000/api/v1.0/task/e71a65a62bc7417097ae906afb88fc4b HTTP/1.1
content-type: application/json
