###
GET http://127.0.0.1:5000/api/v1.0/project/all HTTP/1.1
content-type: application/json

###
POST http://127.0.0.1:5000/api/v1.0/project HTTP/1.1
Content-Type: application/json

{
  "name": "New Project",
  "color": "#000000"
}

###
GET http://127.0.0.1:5000/api/v1.0/project/6964ba78-8dc4-4f23-b525-a0d9fbab865c HTTP/1.1
content-type: application/json

###
DELETE http://127.0.0.1:5000/api/v1.0/project/1 HTTP/1.1
content-type: application/json

###
PUT http://127.0.0.1:5000/api/v1.0/project/1 HTTP/1.1
content-type: application/json

{
  "name": "New api/v1.0/project"
}