###
GET http://127.0.0.1:5000/api/v1.0/project/all HTTP/1.1
content-type: application/json

###
POST http://127.0.0.1:5000/api/v1.0/project HTTP/1.1
Content-Type: application/json

{
  "name": "Project 4",
  "color": "#000000"
}

###
GET http://127.0.0.1:5000/api/v1.0/project/af83c543-bca3-4c68-bd0a-891bed3d95e5 HTTP/1.1
content-type: application/json

### 
PUT http://127.0.0.1:5000/api/v1.0/project/af83c543-bca3-4c68-bd0a-891bed3d95e5 HTTP/1.1
content-type: application/json

{
  "name": "New Project edited"
}

###
PUT http://127.0.0.1:5000/api/v1.0/project/af83c543-bca3-4c68-bd0a-891bed3d95e5 HTTP/1.1
content-type: application/json

{
  "name": "New Project edited 4",
  "color": "#fa00ff"
}

###
DELETE http://127.0.0.1:5000/api/v1.0/project/af83c543-bca3-4c68-bd0a-891bed3d95e5 HTTP/1.1
content-type: application/json
