###
POST http://127.0.0.1:5000/api/v1.0/projects HTTP/1.1
Content-Type: application/json

{
  "name": "Project 23",
  "color": "#000000"
}

###
GET http://127.0.0.1:5000/api/v1.0/projects HTTP/1.1
content-type: application/json

###
GET http://127.0.0.1:5000/api/v1.0/projects/0fab2d6358da4a95ba0c7af8126390af HTTP/1.1
content-type: application/json

### 
PUT http://127.0.0.1:5000/api/v1.0/projects/0fab2d6358da4a95ba0c7af8126390af HTTP/1.1
content-type: application/json

{
  "name": "New Project edited"
}

###
PUT http://127.0.0.1:5000/api/v1.0/projects/0fab2d6358da4a95ba0c7af8126390af HTTP/1.1
content-type: application/json

{
  "name": "New Project edited 8",
  "color": "#fa11ff"
}

###
DELETE http://127.0.0.1:5000/api/v1.0/projects/0fab2d6358da4a95ba0c7af8126390af HTTP/1.1
content-type: application/json
