class EnvironmentVariable:
    ENVIRONMENT = "ENVIRONMENT"
    IS_DEBUG = "IS_DEBUG"
    DATABASE_ENGINE = "DATABASE_ENGINE"
    PY_DB_NAME = "PY_DB_NAME"
    PY_DB_HOST = "PY_DB_HOST"
    PY_DB_USER = "PY_DB_USER"
    PY_DB_PASSWORD = "PY_DB_PASSWORD"
    SESSION_LOCAL = "SESSION_LOCAL"
